spring.application.name=movie-catalog-service
server.port=8081

# Logging Configuration
logging.level.root=INFO
logging.level.com.services.movie_catalog_service=INFO
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} - %logger{36} - %msg%n
logging.pattern.file=%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n
logging.file.name=logs/movie-catalog-service.log
logging.file.max-size=10MB
logging.file.max-history=10
